apiVersion: v1
kind: ConfigMap
metadata:
 name: user
 namespace: roboshop
data:
 MONGO: "true"
 REDIS_URL: "{{ .Values.owner.REDIS_URL }}"
 MONGO_URL: "{{ .Values.owner.MONGO_URL }}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: roboshop
  # these are replica set labels
  labels:
    component: user
    project: roboshop
spec:
  replicas: 1
  selector:
    # these labels are used to select pods
    matchLabels:
      component: user
      project: roboshop
  # pod definition
  template:
    metadata:
      labels:
        component: user
        project: roboshop
    spec:
      containers:
      - name: user
        image: "{{ .Values.owner.imageRepo }}:{{ .Values.owner.imageversion }}"
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: user
        ports:
        - name: liveness-port
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 1
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 1
          periodSeconds: 15
---
#service
apiVersion: v1
kind: Service
metadata:
 name: user
 namespace: roboshop
spec:
  selector:
   component: user
   project: roboshop
  ports:
    - protocol: TCP
      port: {{ .Values.service.servicePort }}
      targetPort: 8080

 